services:
  spark-master:
    image: apache/spark-py:v3.4.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file: .env
    environment:
      - SPARK_MODE=master
    user: "root"
    volumes:
      - spark-logs:/opt/spark/logs
      - spark-work:/opt/spark/work
      - ./.sh:/scripts
    command: ["bash", "/scripts/master.sh"]

  spark-worker-1:
    image: apache/spark-py:v3.4.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    env_file: .env
    environment:
      - SPARK_MODE=worker
    user: "root"
    volumes:
      - spark-logs:/opt/spark/logs
      - spark-work:/opt/spark/work
      - ./.sh:/scripts
    command: ["bash", "/scripts/worker.sh"]

  spark-worker-2:
    image: apache/spark-py:v3.4.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    env_file: .env
    environment:
      - SPARK_MODE=worker
    user: "root"
    volumes:
      - spark-logs:/opt/spark/logs
      - spark-work:/opt/spark/work
      - ./.sh:/scripts
    command: ["bash", "/scripts/worker.sh"]

  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    volumes:
      - ./:/opt/spark/work-dir
      - ./.sh:/scripts
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYTHONPATH=/opt/venv/lib/python3.*/site-packages
    user: "root"
    command: ["bash", "/scripts/submit.sh"]

volumes:
  spark-logs:
  spark-work: